### ISSUE TITLE
 SystemError: google/protobuf/pyext/descriptor.cc:358: bad argument to internal function

### ISSUE THREAD

**Issue by setthawut8** [PyThaiNLP/pythaiasr#7]
Great day to you and thanks a lot for your contribution and determination on this project.

In Colab, I have code 

```
%%capture
!pip install pythaiasr
!pip -q install pydub

import IPython
from pythaiasr import asr
file = "/content/voice data/helloWeeHee.wav"
IPython.display.Audio(file)

#pythaiasr
asr(file, "airesearch/wav2vec2-large-xlsr-53-th")
asr(file, "wannaphong/wav2vec2-large-xlsr-53-th-cv8-newmm")
```

However, after I found an error, try some solutions from Stackoverflow such as importing tensorflow and !pip install pythaiasr[lm]

> SystemError: google/protobuf/pyext/descriptor.cc:358: bad argument to internal function

Now it may involve with tensorflow as I got the same output after importing tensorflow after pythaiasr.

Thank you.

**Comment by wannaphong** [comment]
@setthawut8 Do you use Colab? If you use google colab, I suggest you remove tensorflow before use PyThaiASR. It is bug of Google Colab not PyThaiASR.
