### ISSUE TITLE
Add dockerfile

### ISSUE THREAD

**Issue by wannaphong** [PyThaiNLP/pythaiasr#8]
PyThaASR needs the dockerfile for running this project in the docker.

**Comment by FinnKr** [comment]
What exactly needs to be run in Docker? This does not expose any Endpoint or something right?

**Comment by wannaphong** [comment]
> What exactly needs to be run in Docker? This does not expose any Endpoint or something right?

I don't sure about your question. It needs python, pytorch and other that fellow https://github.com/PyThaiNLP/pythaiasr/blob/main/setup.py#L11. I want the dockerfile that can run this prject in the server. (It is cpu.)

**Comment by FinnKr** [comment]
And how do you want to interact with this project? Or do you just want a docker container containing this project and use it on a server as some kind of insulated shell? Or just push an audio file with it when building the image?

**Comment by wannaphong** [comment]
> And how do you want to interact with this project? Or do you just want a docker container containing this project and use it on a server as some kind of insulated shell? Or just push an audio file with it when building the image?

The choice is yours. My minimum requirement is just a docker container containing this project.

**Comment by FinnKr** [comment]
Okay I'm still not 100% sure if I understand it correctly but I'll make a PR.

**Comment by FinnKr** [comment]
I added a PR: #9
